import React from "react";
import {
  AlertCircle,
  Bell,
  Calendar,
  CheckCircle2,
  Clock,
  Users,
  Wallet,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { KpiCard, KpiCardGrid, StatusBadge } from "@/components/ux";
import PeopleOpsModuleFrame from "@/components/peopleOps/PeopleOpsModuleFrame.jsx";
import PeopleOpsSectionCard from "@/components/peopleOps/PeopleOpsSectionCard.jsx";
import PeopleOpsQuickActions from "@/components/peopleOps/productivity/PeopleOpsQuickActions.jsx";
import PeopleOpsApprovalInbox from "@/components/peopleOps/productivity/PeopleOpsApprovalInbox.jsx";
import PeopleOpsNotificationsPanel from "@/components/peopleOps/productivity/PeopleOpsNotificationsPanel.jsx";
import PeopleOpsRecentActivity from "@/components/peopleOps/productivity/PeopleOpsRecentActivity.jsx";
import PeopleOpsRecentlyViewed from "@/components/peopleOps/productivity/PeopleOpsRecentlyViewed.jsx";
import PeopleOpsFavorites from "@/components/peopleOps/productivity/PeopleOpsFavorites.jsx";
import PeopleOpsWorkflowProgress from "@/components/peopleOps/productivity/PeopleOpsWorkflowProgress.jsx";
import { PEOPLE_OPS_PAYROLL_STATUS_VARIANT } from "@/components/peopleOps/peopleOpsStatusTokens.js";
import {
  buildDashboardPayrollCard,
  buildDashboardPendingActions,
} from "@/peopleOps/peopleOpsEnterpriseModel.js";

function ReportingContextFields({
  context,
  periodOptions = [],
  runOptions = [],
  selectedPeriodId,
  selectedRunId,
  onPeriodChange,
  onRunChange,
  lastRefreshLabel,
}) {
  if (!context) return null;
  return (
    <PeopleOpsSectionCard title="Current Reporting Context" subtitle="Operational views use the selected period and payroll version" icon={Calendar}>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6">
        <label className="space-y-1 xl:col-span-2">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Period</span>
          <select
            className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"
            value={selectedPeriodId || context.periodId || ""}
            onChange={(event) => onPeriodChange?.(event.target.value)}
          >
            {periodOptions.map((row) => (
              <option key={row.periodId} value={row.periodId}>
                {row.periodYm}
              </option>
            ))}
          </select>
        </label>
        <label className="space-y-1 xl:col-span-2">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Version</span>
          <select
            className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"
            value={selectedRunId || context.payrollRunId || ""}
            onChange={(event) => onRunChange?.(event.target.value)}
            disabled={!runOptions.length}
          >
            {runOptions.map((row) => (
              <option key={row.runId} value={row.runId}>
                {row.label}
              </option>
            ))}
          </select>
        </label>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Generated</p>
          <p className="mt-1 text-sm font-medium">{context.generatedAtLabel}</p>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Generated by</p>
          <p className="mt-1 text-sm font-medium">{context.generatedBy}</p>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Status</p>
          <p className="mt-1">
            <StatusBadge variant={PEOPLE_OPS_PAYROLL_STATUS_VARIANT[context.status] || "neutral"} label={context.statusLabel} />
          </p>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Last refresh</p>
          <p className="mt-1 text-sm font-medium">{lastRefreshLabel || "—"}</p>
        </div>
      </div>
    </PeopleOpsSectionCard>
  );
}

export default function PeopleOpsDashboard({
  model,
  breadcrumbs = [],
  employeeCount = 0,
  periodOptions = [],
  runOptions = [],
  selectedPeriodId,
  selectedRunId,
  onPeriodChange,
  onRunChange,
  onNavigatePayroll,
  onNavigateEmployees,
  productivity,
  onQuickAction,
  onOpenRoute,
  recentlyViewed = [],
  favorites = [],
  workflowBusy = false,
  lastRefreshLabel = "",
}) {
  const inboxCount = productivity?.approvalInbox?.length || 0;
  const notificationCount = (productivity?.notifications || []).filter((row) => !row.disabled).length;
  const payrollCard = buildDashboardPayrollCard(model.reportingContext, model.kpis);
  const pending = buildDashboardPendingActions(productivity);

  return (
    <PeopleOpsModuleFrame
      title="Executive Workspace"
      description="Operational command center for payroll, compensation, and workforce actions."
      breadcrumbs={breadcrumbs}
      summary={
        <KpiCardGrid columns={3}>
          <KpiCard
            title={payrollCard.title}
            value={payrollCard.value}
            subtitle={payrollCard.subtitle}
            icon={Wallet}
          />
          <KpiCard
            title="Current Payroll"
            value={model.kpis.currentPayrollLiabilityLabel}
            subtitle={`${model.kpis.employeeCount} employees · Commission ${model.kpis.commissionPayableLabel}`}
            icon={Wallet}
          />
          <KpiCard
            title="Approval Inbox"
            value={String(inboxCount)}
            subtitle={inboxCount ? "Items need action" : "Inbox clear"}
            icon={AlertCircle}
          />
          <KpiCard
            title="Employees"
            value={String(employeeCount)}
            subtitle="Active directory profiles"
            icon={Users}
          />
          <KpiCard
            title="Pending Actions"
            value={String(pending.count)}
            subtitle={pending.summary}
            icon={Clock}
          />
          <KpiCard
            title="Notifications"
            value={String(notificationCount)}
            subtitle={notificationCount ? "Signals to review" : "No alerts"}
            icon={Bell}
          />
        </KpiCardGrid>
      }
    >
      <PeopleOpsQuickActions actions={productivity?.quickActions || []} onAction={onQuickAction} busy={workflowBusy} />

      <ReportingContextFields
        context={model.reportingContext}
        periodOptions={periodOptions}
        runOptions={runOptions}
        selectedPeriodId={selectedPeriodId}
        selectedRunId={selectedRunId}
        onPeriodChange={onPeriodChange}
        onRunChange={onRunChange}
        lastRefreshLabel={lastRefreshLabel}
      />

      <PeopleOpsWorkflowProgress stages={productivity?.workflowProgress || []} />

      <div className="grid gap-4 xl:grid-cols-2">
        <PeopleOpsApprovalInbox items={productivity?.approvalInbox || []} onOpenItem={(item) => onOpenRoute?.(item.route, item)} />
        <PeopleOpsNotificationsPanel
          notifications={productivity?.notifications || []}
          onOpenNotification={(item) => onOpenRoute?.(item.route, item)}
        />
      </div>

      <div className="grid gap-4 xl:grid-cols-2">
        <PeopleOpsFavorites items={favorites} onOpenItem={(item) => onOpenRoute?.(item.route, item)} />
        <PeopleOpsRecentlyViewed items={recentlyViewed} onOpenItem={(item) => onOpenRoute?.(item.route, item)} />
      </div>

      <PeopleOpsRecentActivity items={productivity?.recentActivity || []} />

      <div className="grid gap-4 lg:grid-cols-2">
        <PeopleOpsSectionCard
          title="Workforce Snapshot"
          subtitle="Directory and payroll evidence for the selected run"
          icon={Users}
          rightAction={
            <Button type="button" size="sm" variant="outline" onClick={onNavigateEmployees}>
              View Employees
            </Button>
          }
        >
          <dl className="grid grid-cols-2 gap-3 text-sm">
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Directory count</dt>
              <dd className="mt-1 text-lg font-semibold tabular-nums">{employeeCount}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Employees in run</dt>
              <dd className="mt-1 text-lg font-semibold tabular-nums">{model.kpis.employeeCount}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Paid evidence runs</dt>
              <dd className="mt-1 text-lg font-semibold tabular-nums">{model.kpis.paidEvidenceRuns}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Commission payable</dt>
              <dd className="mt-1 text-lg font-semibold">{model.kpis.commissionPayableLabel}</dd>
            </div>
          </dl>
        </PeopleOpsSectionCard>

        <PeopleOpsSectionCard
          title="Payroll Operations"
          subtitle="Jump into the current payroll cycle"
          icon={CheckCircle2}
          rightAction={
            <Button type="button" size="sm" variant="outline" onClick={onNavigatePayroll}>
              Open Payroll
            </Button>
          }
        >
          {pending.items.length ? (
            <ul className="space-y-2 text-sm">
              {pending.items.map((item) => (
                <li key={item.id}>
                  <button
                    type="button"
                    className="w-full rounded-lg border border-border bg-background px-3 py-2 text-left hover:bg-muted/40"
                    onClick={() => onOpenRoute?.(item.route, item)}
                  >
                    <p className="font-medium text-foreground">{item.title}</p>
                    <p className="text-xs text-muted-foreground">{item.subtitle}</p>
                  </button>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">
              No pending payroll actions for the selected reporting context. Use Quick Actions when a new cycle begins.
            </p>
          )}
        </PeopleOpsSectionCard>
      </div>
    </PeopleOpsModuleFrame>
  );
}
