import React, { useMemo } from "react";
import {
  AlertCircle,
  BarChart3,
  Bell,
  Calendar,
  CheckCircle2,
  Clock,
  Users,
  Wallet,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { KpiCard, KpiCardGrid, StatusBadge } from "@/components/ux";
import PeopleOpsModuleFrame from "@/components/peopleOps/PeopleOpsModuleFrame.jsx";
import PeopleOpsSectionCard from "@/components/peopleOps/PeopleOpsSectionCard.jsx";
import { PEOPLE_OPS_PAYROLL_STATUS_VARIANT } from "@/components/peopleOps/peopleOpsStatusTokens.js";

function ReportingContextFields({
  context,
  periodOptions = [],
  runOptions = [],
  selectedPeriodId,
  selectedRunId,
  onPeriodChange,
  onRunChange,
}) {
  if (!context) return null;
  return (
    <PeopleOpsSectionCard title="Current Period" subtitle="Reporting context for operational views" icon={Calendar}>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
        <label className="space-y-1">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Period</span>
          <select
            className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"
            value={selectedPeriodId || context.periodId || ""}
            onChange={(event) => onPeriodChange?.(event.target.value)}
          >
            {periodOptions.map((row) => (
              <option key={row.periodId} value={row.periodId}>
                {row.periodYm}
              </option>
            ))}
          </select>
        </label>
        <label className="space-y-1">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Payroll version</span>
          <select
            className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"
            value={selectedRunId || context.payrollRunId || ""}
            onChange={(event) => onRunChange?.(event.target.value)}
            disabled={!runOptions.length}
          >
            {runOptions.map((row) => (
              <option key={row.runId} value={row.runId}>
                {row.label}
              </option>
            ))}
          </select>
        </label>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Generated</p>
          <p className="mt-1 text-sm font-medium">{context.generatedAtLabel}</p>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Generated by</p>
          <p className="mt-1 text-sm font-medium">{context.generatedBy}</p>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Status</p>
          <p className="mt-1">
            <StatusBadge variant={PEOPLE_OPS_PAYROLL_STATUS_VARIANT[context.status] || "neutral"} label={context.statusLabel} />
          </p>
        </div>
      </div>
    </PeopleOpsSectionCard>
  );
}

export default function PeopleOpsDashboard({
  model,
  employeeCount = 0,
  periodOptions = [],
  runOptions = [],
  selectedPeriodId,
  selectedRunId,
  onPeriodChange,
  onRunChange,
  onNavigatePayroll,
  onNavigateEmployees,
}) {
  const notifications = useMemo(() => {
    const items = [];
    if (model.kpis.pendingPayrollPeriods > 0) {
      items.push({
        id: "pending-periods",
        tone: "warning",
        title: `${model.kpis.pendingPayrollPeriods} payroll period(s) need attention`,
        detail: "Review draft or submitted periods in Payroll.",
      });
    }
    if (model.kpis.lockedPayrollRuns > 0 && model.kpis.exportedPayrollRuns < model.kpis.lockedPayrollRuns) {
      items.push({
        id: "export-ready",
        tone: "info",
        title: "Locked runs ready for export",
        detail: "Generate export metadata from a locked payroll run.",
      });
    }
    if (model.kpis.promotionEligibleAgents > 0) {
      items.push({
        id: "promotion",
        tone: "success",
        title: `${model.kpis.promotionEligibleAgents} agent(s) promotion eligible`,
        detail: "Review assignments and compensation plans.",
      });
    }
    return items;
  }, [model.kpis]);

  return (
    <PeopleOpsModuleFrame
      title="Operations Dashboard"
      description="Current payroll cycle, workforce snapshot, and items requiring action."
      summary={
        <KpiCardGrid columns={3}>
          <KpiCard
            title="Payroll Status"
            value={model.reportingContext?.statusLabel || "—"}
            subtitle={`${model.reportingContext?.periodLabel || "—"} · ${model.reportingContext?.runVersionLabel || "—"}`}
            icon={BarChart3}
          />
          <KpiCard
            title="Current Payroll"
            value={model.kpis.currentPayrollLiabilityLabel}
            subtitle={`Commission payable ${model.kpis.commissionPayableLabel}`}
            icon={Wallet}
          />
          <KpiCard
            title="Pending Actions"
            value={String(model.kpis.pendingPayrollPeriods)}
            subtitle={`${model.kpis.lockedPayrollRuns} locked · ${model.kpis.exportedPayrollRuns} exported`}
            icon={Clock}
          />
          <KpiCard
            title="Employees"
            value={String(employeeCount)}
            subtitle="Active directory profiles"
            icon={Users}
          />
          <KpiCard
            title="Paid Evidence"
            value={String(model.kpis.paidEvidenceRuns)}
            subtitle="Runs with paid evidence recorded"
            icon={CheckCircle2}
          />
          <KpiCard
            title="Notifications"
            value={String(notifications.length)}
            subtitle={notifications.length ? "Items need review" : "No pending items"}
            icon={Bell}
          />
        </KpiCardGrid>
      }
    >
      <ReportingContextFields
        context={model.reportingContext}
        periodOptions={periodOptions}
        runOptions={runOptions}
        selectedPeriodId={selectedPeriodId}
        selectedRunId={selectedRunId}
        onPeriodChange={onPeriodChange}
        onRunChange={onRunChange}
      />

      <div className="grid gap-4 lg:grid-cols-2">
        <PeopleOpsSectionCard
          title="Pending Actions"
          subtitle="Operational follow-ups for this payroll cycle"
          icon={AlertCircle}
          rightAction={
            <Button type="button" size="sm" variant="outline" onClick={onNavigatePayroll}>
              Open Payroll
            </Button>
          }
        >
          {notifications.length ? (
            <ul className="space-y-2">
              {notifications.map((item) => (
                <li key={item.id} className="rounded-lg border border-border bg-background px-3 py-2.5 text-sm">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-medium text-foreground">{item.title}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">{item.detail}</p>
                    </div>
                    <StatusBadge variant={item.tone} label={item.tone} />
                  </div>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">No pending payroll actions for the current period.</p>
          )}
        </PeopleOpsSectionCard>

        <PeopleOpsSectionCard
          title="Workforce Snapshot"
          subtitle="Quick access to employee directory"
          icon={Users}
          rightAction={
            <Button type="button" size="sm" variant="outline" onClick={onNavigateEmployees}>
              View Employees
            </Button>
          }
        >
          <dl className="grid grid-cols-2 gap-3 text-sm">
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Directory count</dt>
              <dd className="mt-1 text-lg font-semibold tabular-nums">{employeeCount}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Collection efficiency</dt>
              <dd className="mt-1 text-lg font-semibold">{model.kpis.collectionEfficiencyLabel}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Promotion eligible</dt>
              <dd className="mt-1 text-lg font-semibold tabular-nums">{model.kpis.promotionEligibleAgents}</dd>
            </div>
            <div className="rounded-lg border border-border bg-background px-3 py-2">
              <dt className="text-xs text-muted-foreground">Commission payable</dt>
              <dd className="mt-1 text-lg font-semibold">{model.kpis.commissionPayableLabel}</dd>
            </div>
          </dl>
        </PeopleOpsSectionCard>
      </div>
    </PeopleOpsModuleFrame>
  );
}
