import { ROLES } from "./roles";

export const PERMISSIONS = {
  dashboard: [ROLES.AGENT, ROLES.ADMIN, ROLES.EXECUTIVE],
  founderNavigation: [ROLES.EXECUTIVE],
  founderStrategy: [ROLES.EXECUTIVE],
  tenantManagement: [ROLES.EXECUTIVE],
  distributorManagement: [ROLES.EXECUTIVE],
  distributorProvisioning: [ROLES.EXECUTIVE],
  operationsCenter: [ROLES.ADMIN, ROLES.EXECUTIVE],
  visits: [ROLES.AGENT, ROLES.ADMIN],
  collections: [ROLES.AGENT, ROLES.ADMIN],
  labAccount: [ROLES.LAB],
  labs: [ROLES.AGENT, ROLES.ADMIN, ROLES.EXECUTIVE],
  inventory: [ROLES.ADMIN, ROLES.EXECUTIVE],
  orders: [ROLES.ADMIN, ROLES.EXECUTIVE],
  risk: [ROLES.ADMIN, ROLES.EXECUTIVE],
  performance: [ROLES.ADMIN, ROLES.EXECUTIVE],
  insights: [ROLES.ADMIN, ROLES.EXECUTIVE],
  labOrders: [ROLES.LAB],
  purchase: [ROLES.ADMIN, ROLES.EXECUTIVE],
  reorder: [ROLES.ADMIN, ROLES.EXECUTIVE],
  qualificationReview: [ROLES.ADMIN, ROLES.EXECUTIVE],
  notifications: [ROLES.AGENT, ROLES.ADMIN, ROLES.EXECUTIVE, ROLES.LAB],
  predatorDebug: [ROLES.ADMIN, ROLES.EXECUTIVE],
};