export {
  ROLES,
  ALL_ROLE_SLUGS,
  ROLE_LABELS,
  LOGIN_ENABLED_ROLES,
  PILOT_LAUNCH_ROLES,
  NON_PILOT_RELEASE_MESSAGE,
  DISTRIBUTOR_SCOPED_ROLES,
  normalizePlatformRole,
  isLoginEnabledRole,
  isPilotLaunchRole,
  canAuthenticateRole,
  isProvisionableRole,
  isDistributorScopedRole,
  directoryRoleFromPlatformRole,
  platformRoleLabel,
} from "./rolePermissionMatrix.js";
