/** @deprecated Import from hqBoundedReads.js — re-exported for backward compatibility. */
export {
  fetchAdminDashboardBoundedSourceRows,
  fetchAgentVisitsBoundedRows,
  fetchCollectionsBoundedArRows,
  fetchInventoryBoundedRows,
  fetchInventoryLedgerBoundedRows,
  fetchLabsCreditBoundedRows,
  fetchOrderLinesBoundedRows,
  fetchPaymentsBoundedRows,
  fetchQualificationBoundedRows,
  fetchSearchRuntimeBoundedSources,
  invalidateBoundedSourceCache,
  fetchStockDashboardBoundedRows,
  fetchLabCatalogBoundedRows,
  fetchReorderCandidatesBoundedRows,
  invalidateStockDashboardReadCache,
  invalidateLabCatalogReadCache,
  invalidateInventoryLedgerReadCache,
} from "@/api/hqBoundedReads.js";
